## What is a Tensor?

* Tensors are the fundamental building blocks of TensorFlow and machine learning in general.
* They are multi-dimensional arrays that can hold numerical data of various types, such as integers, floats, and booleans.
* You can represent almost any kind of data (images, rows and columns, text) as some kind of tensor.
* In TensorFlow, tensors are represented as `tf.Tensor` objects, which are immutable and have a specified data type and shape.

In [1]:
# import TensorFlow
import tensorflow as tf

<h2 style="color:orange"> Create tensors with tf.constant() (https://www.tensorflow.org/api_docs/python/tf/constant)</h2>

* Creates a constant tensor from a tensor-like object.

In [2]:
# create a scalar
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check the number of dimensions of scalar
scalar.ndim

0

In [4]:
# create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check the dimension of vector
vector.ndim

1

In [6]:
# create a matrix
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
# check the dimension of matrix
matrix.ndim

2

In [8]:
# create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# check the dimension of another_matrix
another_matrix.ndim

2

In [10]:
# create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
# check the dimension of tensor
tensor.ndim

3

* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers

<h2 style="color:orange"> Create tensor with tf.variable()</h2>

* Variables are tensors that can be modified during model training.
* They are used to represent neural network model parameters, such as weights and biases.
* These parameters can then be adjusted to better represent data. For example, your tensors may start with random values to begin with but during training these random values get changed to be more aligned with ideal values that represent your data.
* In TensorFlow, variables are created using the `tf.Variable` class, which initializes the variable with a specified initial value and data type.


https://www.tensorflow.org/api_docs/python/tf/Variable

In [13]:
# create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# Let's try to change one of the elements in "changeable_tensor"
changeable_tensor[0].assign(7)

changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
# Let's try to change one of the elements in "unchangeable_tensor"
unchangeable_tensor[0].assign(7)

unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

<h2 style="color:orange">Create random tensors </h2>

Random tensors are tensors of some arbitrary size which contains random numbers.

`tf.random.Generator`

* Random-number generator.

To create a generator from a seed: **tf.random.Generator.from_seed()**

https://www.tensorflow.org/api_docs/python/tf/random/Generator

`tf.random.normal`

* Outputs random values from a normal distribution.

https://www.tensorflow.org/api_docs/python/tf/random/normal

In [18]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [165]:
tf.random.set_seed(5)
tf.random.normal(shape=[4], mean=0, stddev=1, dtype=tf.float32)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-0.18030666, -0.95028627, -0.03964049, -0.7425406 ], dtype=float32)>

In [166]:
tf.random.set_seed(5)
tf.random.normal(shape=[2, 2], mean=0, stddev=1, dtype=tf.float32, seed=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.3768897 , -0.01258316],
       [-0.169515  ,  1.0824056 ]], dtype=float32)>

`tf.random.set_seed`

* Sets the global random seed.
* Operations that rely on a random seed actually derive it from two seeds: the **global** and **operation-level** seeds.
* tf.random.set_seed(seed) sets the global random seed.
* If neither the global seed nor the operation seed is set: A randomly picked seed is used for this operation.
* If the global seed is set, but the operational seed is not: The system deterministically picks an operation seed in conjunction with the global seed so that it gets a unique random sequence.
* If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.
* If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

https://www.tensorflow.org/api_docs/python/tf/random/set_seed

`tf.random.uniform`

* Outputs random values from a uniform distribution.
* The generated values follow a uniform distribution in the range [minval, maxval). The lower bound minval is included in the range, while the upper bound maxval is excluded.
* For floats, the default range is [0, 1). For ints, at least maxval must be specified explicitly.

https://www.tensorflow.org/api_docs/python/tf/random/uniform

In [155]:
tf.random.uniform(shape=[2])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.7413678 , 0.62854624], dtype=float32)>

In [156]:
tf.random.uniform(shape=[], minval=-1., maxval=0.)

<tf.Tensor: shape=(), dtype=float32, numpy=-0.2597692>

In [157]:
tf.random.uniform(shape=[], minval=5, maxval=10, dtype=tf.int64)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

In [162]:
tf.random.set_seed(5)
tf.random.uniform(shape=[], maxval=3, dtype=tf.int32, seed=10)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [163]:
tf.random.uniform(shape=[], maxval=3, dtype=tf.int32, seed=10)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

<h2 style="color:orange">Shuffle elements in a tensor</h2>

* Randomly shuffles a tensor along its first dimension.

https://www.tensorflow.org/api_docs/python/tf/random/shuffle

In [19]:
# Shuffle the order of elements in a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [20]:
not_shuffled.ndim

2

In [21]:
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [31]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [33]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [22]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed=42) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

If we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seed.

<h2 style="color:orange">tf.ones</h2>

Creates a tensor with all elements set to one (1).

https://www.tensorflow.org/api_docs/python/tf/ones

In [34]:
# Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [36]:
# Create a tensor of all integer format ones
tf.ones(shape=[10, 7], dtype=tf.dtypes.int16)

<tf.Tensor: shape=(10, 7), dtype=int16, numpy=
array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]], dtype=int16)>

<h2 style="color:orange">tf.zeros</h2>

Creates a tensor with all elements set to zero.

https://www.tensorflow.org/api_docs/python/tf/zeros

In [37]:
# Create a tensor of all zeros
tf.zeros(shape=[3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [38]:
# Create a tensor of all integer format zeros
tf.zeros(shape=[3, 4], dtype=tf.dtypes.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

<h2 style="color:orange">Convert NumPy arrays into tensors</h2>

In [39]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [42]:
A = tf.constant(numpy_A, shape=[2, 3, 4])
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [44]:
C = tf.constant(numpy_A, shape=[3, 8])
C

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

<h2 style="color:orange">Getting information from tensors</h2>

When dealing with tensors, you probably want to be aware of the following attributes:

* Shape: The length (number of elements) of each of the dimensions of a tensor.
* Rank: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
* Axis or dimension: A particular dimension of a tensor.
* Size: The total number of items in the tensor.

In [45]:
# Create a rank 4 tensor
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [46]:
# indexing
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [47]:
# shape, rank, size
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [50]:
# Get various attributes of our tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0th axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor))
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0th axis:  2
Elements along the last axis:  5
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor:  120


<h2 style="color:orange">Indexing tensors</h2>

Tensors can be indexed just like Python lists.

In [51]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [53]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :] 

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [54]:
# Get the first element from each dimension from each index except for the 2nd last one
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

<h2 style="color:orange">Reshape tensors</h2>

In [55]:
# Create a rank 2 tensor (2 dimesnions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [58]:
# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [59]:
# Add an extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [60]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

https://www.tensorflow.org/api_docs/python/tf/expand_dims

In [61]:
tf.expand_dims(rank_2_tensor, axis=0) # expand the 0th axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

<h2 style="color:orange">Manipulating tensors (Tensor operations)</h2>

### Basic Operations

`+`, `-`, `*`, `/`

In [62]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7],
                      [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [63]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [64]:
# Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [65]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [66]:
# Division
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [68]:
# We can use tensorflow built-in functions too
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

https://www.tensorflow.org/api_docs/python/tf/math/add

In [69]:
tf.subtract(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

https://www.tensorflow.org/api_docs/python/tf/math/subtract

In [67]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

https://www.tensorflow.org/api_docs/python/tf/math/multiply

In [70]:
tf.divide(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

https://www.tensorflow.org/api_docs/python/tf/math/divide

<h2 style="color:orange">Matrix Multiplication</h2>

In Machine Learning, matrix multiplication is one of the most common tensor operations.

https://www.tensorflow.org/api_docs/python/tf/linalg/matmul

* For matrix multiplication, the number of rows of 1st matrix must be equal to number of columns of 2nd matrix.

In [71]:
print(tensor) 

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [72]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [73]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [76]:
# Try to matrix multiply tensors of different shapes

# Create a (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (2, 3) tensor
Y = tf.constant([[7, 8, 9],
                 [10, 11, 12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>)

In [77]:
tf.linalg.matmul(X, Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [78]:
X @ Y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [79]:
# Try to matrix multiply tensors of same shape

# Create a (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [80]:
tf.matmul(X, Y)

2024-07-17 14:40:01.344071: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: INVALID_ARGUMENT: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2]


InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [81]:
# Let's change the shape of Y
Y = tf.reshape(Y, shape=[2, 3])
Y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [82]:
# Try to matrix muliply X by reshaped Y
X @ Y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [83]:
tf.matmul(X, Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [84]:
# Can do the above operation using transpose
# Create a (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

X.shape, Y.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [86]:
X, tf.transpose(X), tf.reshape(X, shape=[2, 3])

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

https://www.tensorflow.org/api_docs/python/tf/transpose

In [87]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The dot product**

Matrix multiplication is also referred to as the dot product.

You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()` (https://www.tensorflow.org/api_docs/python/tf/tensordot): Tensordot (also known as tensor contraction) sums the product of elements from "a" and "b" over the indices specified by `axes`. 
    - When "a" and "b" are matrices (Order 2), the case `axes=1` is equivalent to matrix multiplication. 
    - When "a" and "b" are matrices (Order 2), the case `axes=[[1], [0]]` is equivalent to matrix multiplication. 
    - When "a" and "b" are matrices (Order 2), the case `axes=0` gives the outer product, a tensor of order 4.
* `@`

In [88]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [90]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [91]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [92]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=[2, 3]))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [93]:
# Check the values of Y, reshape Y and transposed Y
print("Normal Y:")
print(Y, "\n")

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, [2, 3]), "\n")

print("Y transpose:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transpose:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to get satisfied the matrix multiplication rules.

<h2 style="color:orange">Change the data type of a tensor</h2>

In [97]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [100]:
C = tf.constant([7, 10])
C, C.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>,
 tf.int32)

In [99]:
# Change the data type of B from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [101]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

In [102]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16, E_float16.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>,
 tf.float16)

<h2 style="color:orange">Aggregating tensors</h2>

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [103]:
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [104]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

`tf.abs()` computes the absolute value of a tensor. (https://www.tensorflow.org/api_docs/python/tf/math/abs)

In [105]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([37, 62, 72, 22, 88, 54, 20, 13, 13, 99,  2, 97,  4,  9, 96, 47,  9,
       80, 33, 27, 26, 94, 79, 44, 60,  0, 29, 80, 85,  4, 84, 40, 12, 46,
        5, 76, 94, 16, 20, 17, 73, 98, 70, 48, 51, 90, 54, 91, 20, 92])>

In [106]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [107]:
# Get the minimum value of a tensor
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

https://www.tensorflow.org/api_docs/python/tf/math/reduce_min

In [108]:
# Get the maximum value of a tensor
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

https://www.tensorflow.org/api_docs/python/tf/math/reduce_max

In [109]:
# Get the mean of a tensor
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

https://www.tensorflow.org/api_docs/python/tf/math/reduce_mean

In [110]:
# Get the sum of a tensor
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2482>

https://www.tensorflow.org/api_docs/python/tf/math/reduce_sum

In [113]:
# Get the variance of a tensor
tf.reduce_variance(E) # won't work

AttributeError: module 'tensorflow' has no attribute 'reduce_variance'

In [125]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=1065.5105>

https://www.tensorflow.org/api_docs/python/tf/math/reduce_variance

In [116]:
import tensorflow_probability as tfp

tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1065>

https://www.tensorflow.org/probability/api_docs/python/tfp/stats/variance

In [123]:
# Get the standard deviation of a tensor
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=32.64216>

https://www.tensorflow.org/api_docs/python/tf/math/reduce_std

In [124]:
tfp.stats.stddev(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=32.64216>

https://www.tensorflow.org/probability/api_docs/python/tfp/stats/stddev

<h2 style="color:orange">Find the positional maximum and minimum</h2>

In [126]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [127]:
# find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [128]:
# index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [129]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [130]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [131]:
# find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [132]:
# Find the minimum value of F using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

<h2 style="color:orange">Squeezing a tensor (removing all single dimensions)</h2>

In [134]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=[1, 1, 1, 1, 50])
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [135]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [136]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

https://www.tensorflow.org/api_docs/python/tf/squeeze

<h2 style="color:orange">One-hot encoding tensors</h2>

https://www.tensorflow.org/api_docs/python/tf/one_hot

In [137]:
# Create a list of indices
some_list = [0, 1, 2, 3] # could be red, green, blue, purple

# One hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [138]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="I love deep learning", off_value="I also like machine learning")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I love deep learning', b'I also like machine learning',
        b'I also like machine learning', b'I also like machine learning'],
       [b'I also like machine learning', b'I love deep learning',
        b'I also like machine learning', b'I also like machine learning'],
       [b'I also like machine learning', b'I also like machine learning',
        b'I love deep learning', b'I also like machine learning'],
       [b'I also like machine learning', b'I also like machine learning',
        b'I also like machine learning', b'I love deep learning']],
      dtype=object)>

<h2 style="color:orange">Some more mathematical operations</h2>

* Squaring
* Log
* Square root

In [139]:
# Create a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [140]:
# Square the tensor
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

https://www.tensorflow.org/api_docs/python/tf/math/square

In [141]:
# Find the square root of the tensor
tf.sqrt(H)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt] name: 

In [142]:
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

https://www.tensorflow.org/api_docs/python/tf/math/sqrt

In [143]:
# find the log
tf.math.log(H)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Log}}; Op<name=Log; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Log] name: 

In [144]:
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

https://www.tensorflow.org/api_docs/python/tf/math/log

<h2 style="color:orange">Tensors and NumPy</h2>

* TensorFlow interacts beautifully with NumPy arrays.
* One of the main differences between a TensorFlow tensor and a NumPy array is that a TensorFlow tensor can be run on a GPU or TPU (for faster numerical processing).

In [145]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [146]:
# Convert the tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [147]:
# Convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [148]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [149]:
J[0]

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [150]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

<h2 style="color:orange">Some other tensorflow functions</h2>


https://www.tensorflow.org/api_docs/python/tf/all_symbols

<h2 style="color:orange">Exercises</h2>

1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [152]:
# create a scalar
scalar_1 = tf.constant(3.)

# create a vector
vector_1 = tf.constant([3., 5.])

# create a matrix
matrix_1 = tf.constant([[1., 2.],
                        [3., 4.]])

# create a tensor
tensor_1 = tf.constant([[[10., 11., 12.],
                         [13., 14., 15.]], 
                        [[16., 17., 18.],
                         [19., 20., 21.]], 
                        [[22., 23., 24.],
                         [25., 26., 27.]]])

print("Scalar:")
print(scalar_1, "\n")
print("Vector:")
print(vector_1, "\n")
print("Matrix:")
print(matrix_1, "\n")
print("Tensor:")
print(tensor_1)

Scalar:
tf.Tensor(3.0, shape=(), dtype=float32) 

Vector:
tf.Tensor([3. 5.], shape=(2,), dtype=float32) 

Matrix:
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32) 

Tensor:
tf.Tensor(
[[[10. 11. 12.]
  [13. 14. 15.]]

 [[16. 17. 18.]
  [19. 20. 21.]]

 [[22. 23. 24.]
  [25. 26. 27.]]], shape=(3, 2, 3), dtype=float32)


2. Find the shape, rank and size of the tensors you created in 1.

In [153]:
print("The shape of scalar:", scalar_1.shape)
print("The rank of scalar:", scalar_1.ndim)
print("The size of scalar:", tf.size(scalar_1))

print("The shape of vector:", vector_1.shape)
print("The rank of vector:", vector_1.ndim)
print("The size of vector:", tf.size(vector_1))

print("The shape of matrix:", matrix_1.shape)
print("The rank of matrix:", matrix_1.ndim)
print("The size of matrix:", tf.size(matrix_1))

print("The shape of tensor:", tensor_1.shape)
print("The rank of tensor:", tensor_1.ndim)
print("The size of tensor:", tf.size(tensor_1))

The shape of scalar: ()
The rank of scalar: 0
The size of scalar: tf.Tensor(1, shape=(), dtype=int32)
The shape of vector: (2,)
The rank of vector: 1
The size of vector: tf.Tensor(2, shape=(), dtype=int32)
The shape of matrix: (2, 2)
The rank of matrix: 2
The size of matrix: tf.Tensor(4, shape=(), dtype=int32)
The shape of tensor: (3, 2, 3)
The rank of tensor: 3
The size of tensor: tf.Tensor(18, shape=(), dtype=int32)


3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [154]:
# create two random tensors with values between 0 and 1 & shape [5, 300]
tf.random.set_seed(42)
random_tensor_1 = tf.random.uniform(shape=[5, 300])

random_tensor_2 = tf.random.uniform(shape=[5, 300])

random_tensor_1, random_tensor_2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
         0.03699052],
        [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
         0.2200619 ],
        [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
         0.00726748],
        [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
         0.9409125 ],
        [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
         0.44135118]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.8280058 ],
        [0.36690

4. Multiply the two tensors you created in 3 using matrix multiplication.

In [168]:
# multiplying random_tensor_1 & random_tensor_2 using tf.matmul()
tf.matmul(random_tensor_1, tf.transpose(random_tensor_2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.333435, 73.40498 , 77.15962 , 73.98368 , 80.90054 ],
       [75.14635 , 68.80437 , 74.24302 , 71.841835, 75.602066],
       [79.7594  , 75.64456 , 77.797585, 74.74873 , 80.559845],
       [75.08526 , 69.06406 , 74.30776 , 72.27615 , 76.05668 ],
       [85.0569  , 74.266266, 78.00686 , 74.88679 , 83.13417 ]],
      dtype=float32)>

5. Multiply the two tensors you created in 3 using dot product.

In [169]:
# multiplying random_tensor_1 & random_tensor_2 using tf.tensordot()
tf.tensordot(random_tensor_1, tf.transpose(random_tensor_2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.333435, 73.40498 , 77.15962 , 73.98368 , 80.90054 ],
       [75.14635 , 68.80437 , 74.24302 , 71.841835, 75.602066],
       [79.7594  , 75.64456 , 77.797585, 74.74873 , 80.559845],
       [75.08526 , 69.06406 , 74.30776 , 72.27615 , 76.05668 ],
       [85.0569  , 74.266266, 78.00686 , 74.88679 , 83.13417 ]],
      dtype=float32)>

6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [170]:
# create a tensor with random values between 0 and 1 with shape [224, 224, 3]
tf.random.set_seed(42)
random_tensor_3 = tf.random.uniform(shape=[224, 224, 3])
random_tensor_3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.6645621 , 0.44100678, 0.3528825 ],
        [0.46448255, 0.03366041, 0.68467236],
        [0.74011743, 0.8724445 , 0.22632635],
        ...,
        [0.42612267, 0.09686017, 0.16105258],
        [0.1487099 , 0.04513884, 0.9497483 ],
        [0.4393103 , 0.28527975, 0.96971095]],

       [[0.73308516, 0.5657046 , 0.33238935],
        [0.8838178 , 0.87544763, 0.56711245],
        [0.8879347 , 0.47661996, 0.42041814],
        ...,
        [0.7716515 , 0.9116473 , 0.3229897 ],
        [0.43050945, 0.83253574, 0.45549798],
        [0.29816985, 0.9639522 , 0.3316357 ]],

       [[0.41132426, 0.2179662 , 0.53570235],
        [0.5112119 , 0.6484759 , 0.8894886 ],
        [0.42459428, 0.20189774, 0.85781324],
        ...,
        [0.02888799, 0.3995477 , 0.11355484],
        [0.68524575, 0.04945195, 0.17778492],
        [0.97627187, 0.79811585, 0.9411576 ]],

       ...,

       [[0.9019445 , 0.27011132, 0.8090267 ],
        [0.32

7. Find the min and max values of the tensor you created in 6 along the first axis.

In [171]:
print("Minimum value of the tensor random_tensor_3:", tf.reduce_min(random_tensor_3))
print("Maximum value of the tensor random_tensor_3:", tf.reduce_max(random_tensor_3))

Minimum value of the tensor random_tensor_3: tf.Tensor(3.5762787e-07, shape=(), dtype=float32)
Maximum value of the tensor random_tensor_3: tf.Tensor(0.999998, shape=(), dtype=float32)


8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [173]:
tf.random.set_seed(42)
random_tensor_4 = tf.random.uniform(shape=[1, 224, 224, 3])
# print(random_tensor_4)
print(random_tensor_4.shape)

# squeezing the tensor
squeezed_random_tensor_4 = tf.squeeze(random_tensor_4)
# print(squeezed_random_tensor_4)
print(squeezed_random_tensor_4.shape)

(1, 224, 224, 3)
(224, 224, 3)


9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [174]:
tensor_3 = tf.constant([1, 23, 15, 8, 38, 20, 13, 22, 5, 19])

# index with maximum value
tf.argmax(tensor_3)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [176]:
tensor_3[tf.argmax(tensor_3)].numpy()

38

10. One-hot encode the tensor you created in 9.

In [180]:
depth=38
tf.one_hot(tensor_3, depth)

<tf.Tensor: shape=(10, 38), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0